# setup get aware prompt
#export GITAWAREPROMPT=$HOME/.sh/git-aware-prompt
#source "${GITAWAREPROMPT}/main.sh"

#    ~  -  -  ~  -      -   -   - -- >>>>>>---- DOT ---->
source ~/.dot.conf
export DOT_SHELL="bash"
source $DOT/bin/dot-source.sh
