# setup get aware prompt
#export GITAWAREPROMPT=$HOME/.sh/git-aware-prompt
#source "${GITAWAREPROMPT}/main.sh"

# setup tool version env vars
export V_NODE_VERSION="v4.4.4"
export V_BASH_VERSION="v4.3"
export V_GO_VERSION="V1.6"

#    ~  -  -  ~  -      -   -   - -- >>>>>>---- DOT ---->
source ~/.dot.conf
export DOT_SHELL="bash"
source $DOT/src/dot-source.sh

#if [[ ! "$TMUX" ]];then 
  #tmux -2 -S /tmp/tmux-session -L default
#fi

# added by travis gem
[ -f /Users/slugbyte/.travis/travis.sh ] && source /Users/slugbyte/.travis/travis.sh

PATH=$PATH:/Applications/SuperCollider.app/Contents/MacOS
SCVIM_TAGFILE=$HOME/.sctags

export PATH="$HOME/.node/bin:$PATH"
export NODE_PATH="$HOME/.node/lib/node_modules"


alias lulwat="echo 'hello world'"
