" SEtup vundle
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" default
Plugin 'L9'
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

" UI n stuff 
Plugin 'flazz/vim-colorschemes'
Plugin 'airblade/vim-gitgutter'  
Plugin 'bling/vim-airline'  
Plugin 'vim-airline/vim-airline-themes'
Plugin 'bling/vim-bufferline'

" y not type less
Plugin 'Valloric/YouCompleteMe'
Plugin 'marijnh/tern_for_vim'
Plugin 'scrooloose/syntastic'
Plugin 'Chiel92/vim-autoformat'

" better syntax
Plugin 'jelera/vim-javascript-syntax'

" file nav
Plugin 'kien/ctrlp.vim'

" handy tools
Plugin 'matze/vim-move' 
Plugin 'scrooloose/nerdcommenter'
Plugin 'godlygeek/tabular'
Plugin 'christoomey/vim-tmux-navigator'

" version vontrol 
Plugin 'tpope/vim-rhubarb'
Plugin 'tpope/vim-fugitive'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" general conf
set backspace=2           " make backspace work like all other apps
set number                " turn on the line numbers
set incsearch             " vim starts searching while typing search string
set expandtab
set tabstop=2             " tabset three spaces
set shiftwidth=2          " tabset three space
set ff=mac                " set file format to mac
syntax enable             " syntax always on
set wildmenu              " enable tab completion
set wildmode=list:longest " configure tab completion
set t_Co=256              " set termcolors to 256
set encoding=utf8         " set standared encoding as utf8
set ruler                 " allways show the current position
set laststatus=2          " allways show the status line
set cursorline            " allways show a line where the curser is
colorscheme jellybeans    " set the color scheme
set undodir=~/.vim/undoHist
set undofile

" Key Bindings
imap ii <Esc>
let mapleader = "\<Space>"
noremap H ^
noremap L $

" copy and paste from clipboard 
map <leader>cp "+y
map <leader>cv "+p

" leader s = syntastic
nnoremap <silent> <leader>s :SyntasticCheck<CR>  

" leader sp = set paste 
nnoremap <silent> <leader>sp :set paste<CR>

" leader sn = set nopaste
nnoremap <silent> <leader>sn :set nopaste<CR>

" leader p = control p
nnoremap <silent> <leader>p :CtrlPMixed<CR>

" vim-autoformat
nnoremap <silent> <leader>b :Autoformat<CR>

" Vim-Airline
let g:airline_powerline_fonts = 1           " Use powerline fonts for
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline_theme='base16'


" setup vim-move to use Ctl key
let g:move_key_modifier  = 'C'

" Syntastic
let g:syntastic_mode_map = { 'mode': 'passive',     
      \ 'active_filetypes': [],     
      \ 'passive_filetypes': [] } 
let g:syntastic_check_on_open=1
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '!'
let g:syntastic_auto_loc_list = 1

let g:ycm_global_ycm_extra_conf = '.vim/bundle/YouCompleteMe/cpp/ycm/.ycm_extra_conf.py'

if has('mouse')		   " if there is a mouse avalible allow it
  set mouse=a
endif
