export ZSH=/Users/slugbyte/.oh-my-zsh
ZSH_THEME="theunraveler"
DISABLE_AUTO_UPDATE="true"
plugins=(git git-extras docker httpie zsh-syntax-highlighting) 

source $ZSH/oh-my-zsh.sh
export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix nvm)/nvm.sh"

# ~   ~  -  -  ~  -      -   -   - -- >>>>>>---- DOT ---->
source ~/.dot.conf
export DOT_SHELL="zsh"
source $DOT/bin/dot-source.sh

alias v="nvim"
alias vim="nvim"
