# shorts for git
alias ga='git add -A'
alias gb='git branch -a'
alias gu="git remote update -p"
alias gc='git commit -a -m'
alias gs='git status'
alias gp='git push origin'
alias gpu='git push upstream'
alias gl='git pull origin'
alias glu='git pull upstream'
alias gch='git checkout'
alias glog='git log --graph --max-count=10'
alias gdiff='git diff'
alias gdtool='git difftool'
alias gmerge='git merge'
alias gmtool='git mergetool'
alias gstash='git stash'
alias greset='git reset'
alias gmv='git mv'
alias gclone='git clone'
alias gremote='git remote'
